ProjetFinEtude/Models/Chat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetFinEtude.Models
{
    public class Chat
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string Title { get; set; }
        [Required]
        [MaxLength(500)]
        public string Message { get; set; }

        [Required]
        public string FromId { get; set; }
        [Required]
        public string ToId { get; set; }


        public DateTime SendDate { get; set; }

        public ApplicationUser From { get; set; }
        public ApplicationUser To { get; set; }
    }
}

ProjetFinEtude/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetFinEtude.Models
{
    public class Teacher
    {
        public int Id { get; set; }
        [Required, MaxLength(10), MinLength(10)]
        public string NationalId { get; set; }

        [Required, MaxLength(50)]
        public string FirstName { get; set; }
        [MaxLength(50)]
        public string MidName { get; set; }
        [Required, MaxLength(50)]
        public string LastName { get; set; }

        [Required]
        public char Gender { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime DateBirth { get; set; }

        [MaxLength(250)]
        public string ImagePath { get; set; }

        public ApplicationUser ApplicationUser { get; set; }
        public List<Subject> Subjects { get; set; }
    }
}

ProjetFinEtude/Controllers/HomeController.cs
using ProjetFinEtude.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetFinEtude.Controllers
{
    [AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjetFinEtude/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetFinEtude.Data;
using ProjetFinEtude.Models;
using Microsoft.AspNetCore.Identity;
using ProjetFinEtude.ViewModel;
using System.Diagnostics;
using ProjetFinEtude.Constants;
using Microsoft.AspNetCore.Authorization;

namespace ProjetFinEtude.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class TeachersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;


        public TeachersController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager
            )
        {
            _userManager = userManager;
            _context = context;
            _signInManager = signInManager;
        }

        public async Task<IActionResult> Home()
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user.TeacherId;
            if (userId == null) return NotFound();

            var subjects = await _context.Subjects
                .Include(c => c.Class).Include(s => s.SubjectDetails)
                .Where(s => s.TeacherId == userId)
                .ToListAsync();

            ViewData["coursesList"] = subjects.Select(s => s.Class.Name + " - " + s.SubjectDetails.Name).ToArray();

            var classesIds = subjects
                .Select(s => s.ClassId)
                .ToList();
            var courseIds = subjects
               .Select(s => s.Id)
               .ToList();

            var exams = await _context.Quizzes.Where(q => courseIds.Contains((int)q.SubjectId)).CountAsync();
            var students = await _context.Students.Where(c => classesIds.Contains((int)c.ClassId)).ToListAsync();

            ViewData["AllStudents"] = students.Count;
            ViewData["AllParents"] = students.Where(s => s.ParentId != null).Count();
            ViewData["Exams"] = exams;
            ViewData["AllClasses"] = courseIds.Count();
            ViewData["Male"] = students.Where(s => s.Gender == 'M').Count();
            ViewData["Female"] = students.Where(s => s.Gender == 'F').Count();


            ////
            var currentUserId = _userManager.GetUserId(User);
            var viewModel = new AdminHomeViewModel
            {
                Notice = await _context.Notices.OrderByDescending(e => e.PostDateTime.Date).Take(10).ToListAsync(),
                Chats = await _context.Chats.OrderByDescending(o => o.SendDate)
                .Where(c => c.ToId == currentUserId).Take(10).ToListAsync()
            };

            return View(viewModel);
        }

        //profile
        public async Task<IActionResult> Profile()
        {
            var userId = _userManager.GetUserId(User);
            if (userId == null) return NotFound();
            var user = await _userManager.Users.Where(u => u.Id == userId)
                .Include(t => t.Teacher).FirstOrDefaultAsync();
            if (user == null) return NotFound();

            var viewModel = new TeacherViewModel
            {
                AccountId = userId,
                Id = user.Teacher.Id,
                UserName = user.UserName,
                FirstName = user.Teacher.FirstName,
                MidName = user.Teacher.MidName,
                LastName = user.Teacher.LastName,
                Email = user.Email,
                Phone = user.PhoneNumber,
                DateBirth = user.Teacher.DateBirth,
                NationalId = user.Teacher.NationalId,
                Gender = user.Teacher.Gender
            };

            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> Profile(string oldPassword, string newPassword, string confirmPassword)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return BadRequest("Failed,try again");
            }
            if (oldPassword == null || newPassword == null || confirmPassword == null)
            {
                return BadRequest("Please Fill All Failed");
            }
            if (newPassword != confirmPassword)
            {
                return BadRequest("Password and rePassword not match");
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(user,
                    oldPassword, newPassword);
            if (!changePasswordResult.Succeeded)
            {
                string temp = "";
                foreach (var error in changePasswordResult.Errors)
                {
                    temp += error.Description + "<br/>";
                }
                return BadRequest(temp);
            }

            await _signInManager.RefreshSignInAsync(user);
            return Ok("Update success");
        }
        public async Task<IActionResult> Courses(string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            var user = await _userManager.GetUserAsync(User);
            var classes = await _context.Subjects
                .Where(e => e.TeacherId == user.TeacherId).OrderBy(by => by.StartTime)
                .Include(c => c.Class).Include(t => t.Teacher).Include(s => s.SubjectDetails)
                .ToListAsync();

            if (!String.IsNullOrEmpty(searchString))
            {
                classes = classes.Where(s => s.Class.Name.StartsWith(searchString)
                || s.Class.Year.ToString().StartsWith(searchString)
                || s.SubjectDetails.Name.StartsWith(searchString)
                 ).ToList();
                return View(classes);
            }

            return View(classes);
        }
        public async Task<IActionResult> TakeAttendance(int? classId, int? subjectId)
        {
            if (classId == null || subjectId == null)
            {
                return NotFound();
            }

            var user = await _userManager.GetUserAsync(User);

            var students = await _context.Students.Where(s => s.ClassId == classId).ToListAsync();

            var studentAttend = students.Select(s => new CheckboxViewModel
            {
                Id = s.Id,
                NationalId = s.NationalId,
                DisplayValue = $"{s.FirstName} {s.MidName} {s.LastName}",
            }).ToList();

            ViewData["className"] = _context.Classes.Where(c => c.Id == classId).FirstOrDefaultAsync().Result.Name;

            var viewModel = new AttendanceViewModel
            {
                AttendencesList = studentAttend,
            };
            AttendanceViewModel.SubjectId = (int)subjectId;
            AttendanceViewModel.ClassId = (int)classId;
            return View(viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TakeAttendance(AttendanceViewModel model)
        {
            if (!ModelState.IsValid) return NotFound();

            var currentLesson = await _context.Lessons.Where(e =>
                  e.Date.Date == DateTime.Now.Date
                  && e.SubjectId == AttendanceViewModel.SubjectId
                 ).FirstOrDefaultAsync();
            if (currentLesson != null)
            {
                _context.Lessons.Remove(currentLesson);
                await _context.SaveChangesAsync();
            }

            Lesson lesson = new Lesson
            {
                SubjectId = AttendanceViewModel.SubjectId,
                Date = DateTime.Now
            };
            _context.Lessons.Add(lesson);
            await _context.SaveChangesAsync();
            var lessonId = _context.Lessons.OrderByDescending(b => b.Id).FirstOrDefaultAsync().Result.Id;

            var attend = model.AttendencesList.Where(e => e.IsSelected).ToList();
            var absence = model.AttendencesList.Where(e => e.IsSelected == false).ToList();

            var attendStudent = attend.Select(e => new Attendance
            {
                LessonId = lessonId,
                StudentId = e.Id
            });
            var absenceStudent = absence.Select(e => new Absence
            {
                LessonId = lessonId,
                StudentId = e.Id,
                Resone = "NONE"
            });
            _context.Attendances.AddRange(attendStudent);
            _context.Absences.AddRange(absenceStudent);

            await _context.SaveChangesAsync();

            return RedirectToAction("ViewAttendance", new
            {
                subjectId = AttendanceViewModel.SubjectId
            });
        }
        [HttpGet]
        public async Task<IActionResult> ViewAttendance(int? subjectId)
        {
            if (subjectId == null) return NotFound();

            var currentUser = await _userManager.GetUserAsync(User);
            var currentUserId = currentUser.TeacherId;

            if (currentUserId == null) return NotFound();

            var subjects = await _context.Subjects.Include(s => s.SubjectDetails).Include(c => c.Class)
                .Where(s => s.Id == subjectId).FirstOrDefaultAsync();

            var lessons = await _context.Lessons
              .Where(e => e.SubjectId == subjects.Id)
              .OrderBy(by => by.Date).ToListAsync();

            var students = await _context.Students
                .Where(e => e.ClassId == subjects.ClassId).ToListAsync();

            var lastSession = lessons
                 .Where(e => e.SubjectId == subjectId &&
                 e.Date.ToString("yyyy/MM/dd").Equals(DateTime.Now.ToString("yyyy/MM/dd")))
                 .FirstOrDefault();

            var studentsAttends = students.Select(s => new StudentAttendViewModel
            {
                Student = s,

ProjetFinEtude/Views/Teachers/AllStudents.cshtml
@model PaginatedList<Student>
@{
    ViewData["Title"] = "AllStudents";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>All Students</h2>
<hr />
<div class="row">

    <div class="col-md-6">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary">
                    Filter List By
                </h6>
            </div>
            <form asp-action="AllStudents" method="get">
                <div class="card-body overflow-hidden">
                    <div class="row align-content-center">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="classId">Class</label>
                                <select class="form-control"
                                        name="classId" id="classId"
                                        asp-items="ViewBag.classes">
                                    <option selected value="">---select Class---</option>
                                </select>
                            </div>
                        </div>

                    </div>
                </div>
                <div class="card-footer text-muted">
                    <button class="btn btn-outline-success">
                        <i class="fas fa-sort-alpha-up"></i> Filter
                    </button>
                    <button class="btn btn-outline-secondary" id="resetBtn">
                        <i class="fas fa-undo"></i> Reset
                    </button>
                </div>

            </form>
        </div>
    </div>




    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary">
                    All Student
                </h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th scope="col">   Id  </th>
                                <th scope="col">   Name  </th>
                                <th scope="col">   Gender  </th>
                                <th scope="col">   Date Of Brith  </th>
                                <th scope="col"> Class  </th>
                                <th scope="col"> Parent  </th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th scope="col">   Id  </th>
                                <th scope="col">   Name  </th>
                                <th scope="col">   Gender  </th>
                                <th scope="col">   Date Of Brith  </th>
                                <th scope="col"> Class  </th>
                                <th scope="col"> Parent  </th>

                            </tr>
                        </tfoot>
                        <tbody>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.NationalId</td>
                                    <td>@item.FirstName @item.MidName @item.LastName</td>
                                    <td>@(item.Gender=='M'?"Male":"Female")</td>
                                    <td>@item.DateBirth.ToString("yyyy/MM/dd")</td>
                                    <td>@item.Class.Name</td>
                                    @if (item.Parent != null)
                                    {
                                        <td>
                                            <a asp-action="AllParents"
                                               asp-controller="Teachers"
                                               class="btn btn-outline-info btn-sm">
                                                @item.Parent.NationalId - @item.Parent.FirstName @item.Parent.LastName
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td>NONE</td>
                                    }
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer text-muted text-center">
                @{
                    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                }

                <a asp-action="AllStudents"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   class="btn btn-outline-secondary @prevDisabled">
                    Previous
                </a>
                <a asp-action="AllStudents"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   class="btn btn-outline-primary @nextDisabled">
                    Next
                </a>
            </div>
        </div>
    </div>
</div>


@section Scripts{
    <script src="~/lib/select2/js/select2.min.js"></script>

    <script>
        $("#classId").select2();

        $("#resetBtn").on("click", function () {
            $("select").each(function () {
                $(this).prop('selectedIndex', 0);
            })
        })
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

ProjetFinEtude/Views/Teachers/Courses.cshtml
@model IEnumerable<Subject>
@{
    ViewData["Title"] = "My Courses";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>My Courses</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary">
                    Year:2021 - Semester: 1
                </h6>

                <form asp-action="Courses" method="get" class="form-inline mt-2">
                    <div class="input-group mb-3">
                        <input type="text" name="SearchString" class="form-control mr-sm-2" id="SearchStringId"
                               value="@ViewData["CurrentFilter"]"
                               placeholder="Search by..." />
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="submit">Search</button>
                        </div>
                    </div>

                </form>

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th scope="col">Class</th>
                                <th scope="col">Subject</th>
                                <th scope="col">Time</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th scope="col">Class</th>
                                <th scope="col">Subject</th>
                                <th scope="col">Time</th>
                                <th scope="col">Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Class.Name</td>
                                    <td>@item.SubjectDetails.Name</td>
                                    <td>
                                        @( $"{item.StartTime.ToString(@"hh\:mm")} - {item.EndTime.ToString(@"hh\:mm")}" )
                                    </td>
                                    <td class="text-nowrap">
                                        <div class="dropdown mb-4">
                                            <button class="btn btn-outline-primary dropdown-toggle btn-sm"
                                                    type="button" id="drop-@item.Id"
                                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Action
                                            </button>
                                            <div class="dropdown-menu animated--fade-in" aria-labelledby="drop-@item.Id">
                                                <a class="dropdown-item p-5rem "
                                                   asp-action="TakeAttendance"
                                                   asp-route-subjectId="@item.Id"
                                                   asp-route-classId="@item.ClassId">
                                                    <i class="far fa-calendar-check"></i> Take Attendance
                                                </a>
                                                <a class="dropdown-item p-5rem "
                                                   asp-action="ViewAttendance"
                                                   asp-route-subjectId="@item.Id"><i class="fas fa-calendar-check"></i> View Attendance</a>
                                                <a class="dropdown-item p-5rem" asp-action="ExamResult"
                                                   asp-route-id="@item.Id"><i class="fas fa-check"></i> Add Exam Result</a>
                                                <a class="dropdown-item p-5rem" asp-action="ViewExamResult"
                                                   asp-route-id="@item.Id"><i class="fas fa-chart-bar"></i> View Exams Results</a>
                                                <a class="dropdown-item p-5rem " asp-controller="Grades"
                                                   asp-action="GiveMarks" asp-route-id="@item.Id">
                                                    <i class="fas fa-award"></i> Give Marks
                                                </a>
                                                <a class="dropdown-item p-5rem "
                                                   asp-action="SendMessageToStudents"
                                                   asp-controller="Teachers"
                                                   asp-route-id="@item.ClassId">
                                                    <i class="fas fa-envelope"></i> Message Students
                                                </a>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer text-muted">


            </div>
        </div>
    </div>
</div>

ProjetFinEtude/Views/Teachers/ExamResult.cshtml
@model ExamViewModel
@{
    ViewData["Title"] = "Exam Result";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>Select Exam</h2>
<hr />

<div class="row">
    <div class="col-md-7">
        <form asp-action="AddExamResult" method="get">
            <div class="card shadow mb-4">
                <div class="card-header text-primary">
                    <h6>
                        Select Exam
                    </h6>
                </div>
                <input type="hidden" asp-for="SubjectId" />
                <div class="card-body">
                    <div class="form-group">
                        <h6>Class - Subject</h6>
                        <p class="lead">@Model.Subject.Class.Name -  @Model.Subject.SubjectDetails.Name </p>
                    </div>
                    <div class="form-group">
                        <label for=""></label>
                        <select asp-for="ExamId" asp-items="@Model.ExamList" name="id" class="form-control" required>
                            <option value="" selected disabled>---Select Exam---</option>
                        </select>
                        <span class="text-danger" asp-validation-for="ExamId"></span>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <input type="submit" class="btn btn-primary" value="Next" />
                    <a class="btn btn-outline-secondary" asp-action="Courses" asp-controller="Teachers">Back</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetFinEtude/Views/Teachers/ShowMessage.cshtml
@model Chat
@{
    ViewData["Title"] = "Show Message";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>Message From @Model.From.UserName</h2>
<hr />
<div class="row">
    <div class="col-md-7">
        <div class="card shadow">
            <div class="card-body">
                <h4>
                    From: @Model.From.UserName
                </h4>
                <h5>title: @Model.Title</h5>
                <p class="lead">
                    Message:@Model.Message
                </p>
            </div>
            <div class="card-footer">
                <a asp-action="Chat" asp-route-toId="@Model.FromId" class="btn btn-primary">Replay</a>
                <a asp-action="ShowChat" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </div>
</div>

ProjetFinEtude/Views/Teachers/ShowNotice.cshtml
@model Notice

@{
    ViewData["Title"] = "Notice board";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>Notice Board</h2>
<hr />

<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary">
                    @Model.Title
                </h6>
            </div>
            <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Title)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Title)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.PostDateTime)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.PostDateTime)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Description)
                    </dd>
                </dl>
            </div>
            <div class="card-footer text-muted">
                <a class="btn btn-secondary" asp-action="Home" asp-controller="Teachers">Back</a>
            </div>
        </div>
    </div>
</div>