ProjetFinEtude/Models/Grade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjetFinEtude.Models
{
    public class Grade
    {
        public int Id { get; set; }
        public double? FirstMark { get; set; }
        public double? MidtMark { get; set; }
        public double? FinalMark { get; set; }
        public double? ActivityMark { get; set; }
        public double? Total { get; set; }



        public int SubjectId { get; set; }
        public Subject Subject { get; set; }


        public int StudentId { get; set; }
        public Student Student { get; set; }
    }
}

ProjetFinEtude/Controllers/GradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjetFinEtude.Data;
using ProjetFinEtude.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using ProjetFinEtude.ViewModel;

namespace ProjetFinEtude.Controllers
{
    [Authorize(Roles = "Teacher")]
    public class GradesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public GradesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var subject = await GetSubjecsAsync();
            return View(subject);
        }

        public async Task<IActionResult> ViewMarks(int? id)
        {
            if (id == null) return NotFound();
            var subject = await _context.Subjects
                .Include(c => c.Class).Include(s => s.SubjectDetails)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (subject == null) return NotFound();
            var students = await _context.Students.Where(c => c.ClassId == subject.ClassId).ToListAsync();
            var gradesList = await _context.Grades
                .Include(s => s.Student)
                .Where(g => g.SubjectId == subject.Id).ToListAsync();

            var studentGradeViewModel = gradesList.Select(g => new GradeViewModel
            {
                StudentId = g.Student.Id,
                StudentName = $"{g.Student.FirstName} {g.Student.MidName} {g.Student.LastName}",
                FirstMark = g.FirstMark.HasValue ? (double)g.FirstMark : 0,
                MidtMark = g.MidtMark.HasValue ? (double)g.MidtMark : 0,
                FinalMark = g.FinalMark.HasValue ? (double)g.FinalMark : 0,
                ActivityMark = g.ActivityMark.HasValue ? (double)g.ActivityMark : 0,
                GradeId = g.Id,
                Total = g.Total.HasValue ? (double)g.Total : 0
            }).ToList();
            var viewModel = new AddGradeViewModel
            {
                StudentsGrades = studentGradeViewModel,
                ClassName = subject.Class.Name,
                SubjectName = subject.SubjectDetails.Name,
                ClassAvarage = gradesList.Select(g => g.Total.HasValue ? (double)g.Total : 0).Average(),
                FirstAvarage = gradesList.Select(g => g.FirstMark.HasValue ? (double)g.FirstMark : 0).Average(),
                MidAvarage = gradesList.Select(g => g.MidtMark.HasValue ? (double)g.MidtMark : 0).Average(),
                FinalAvarage = gradesList.Select(g => g.FinalMark.HasValue ? (double)g.FinalMark : 0).Average(),
            };
            return View(viewModel);
        }
        [HttpGet]
        public async Task<IActionResult> GiveMarks(int? id)
        {
            if (id == null) return NotFound();
            var subject = await _context.Subjects
                .Include(c => c.Class).Include(s => s.SubjectDetails)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (subject == null) return NotFound();
            var students = await _context.Students.Where(c => c.ClassId == subject.ClassId).ToListAsync();
            var gradesList = await _context.Grades
                .Include(s => s.Student)
                .Where(g => g.SubjectId == subject.Id).ToListAsync();
            if (gradesList.Count == 0)
            {
                var subjectGradeList = new List<Grade>();
                for (int i = 0; i < students.Count; i++)
                {
                    subjectGradeList.Add(new Grade
                    {
                        StudentId = students[i].Id,
                        SubjectId = (int)id
                    });
                }
                _context.Grades.AddRange(subjectGradeList);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    throw new Exception(ex.Message);
                }
                gradesList = await _context.Grades
                    .Include(s => s.Student)
                    .Where(g => g.SubjectId == subject.Id).ToListAsync();
            }

            var studentGradeViewModel = gradesList.Select(g => new GradeViewModel
            {
                StudentId = g.Student.Id,
                StudentName = $"{g.Student.FirstName} {g.Student.MidName} {g.Student.LastName}",
                FirstMark = g.FirstMark.HasValue ? (double)g.FirstMark : 0,
                MidtMark = g.MidtMark.HasValue ? (double)g.MidtMark : 0,
                FinalMark = g.FinalMark.HasValue ? (double)g.FinalMark : 0,
                ActivityMark = g.ActivityMark.HasValue ? (double)g.ActivityMark : 0,


                GradeId = g.Id
            }).ToList();
            var viewModel = new AddGradeViewModel
            {
                StudentsGrades = studentGradeViewModel,
                ClassName = subject.Class.Name,
                SubjectName = subject.SubjectDetails.Name
            };
            return View(viewModel);
        }
        [HttpPost]
        public async Task<IActionResult> GiveMarks(AddGradeViewModel model)
        {
            if (!ModelState.IsValid) return NotFound();

            var gradeListIds = model.StudentsGrades.Select(g => g.GradeId).ToList();
            var gradeList = await _context.Grades.Where(g => gradeListIds.Contains(g.Id)).ToListAsync();
            var modelData = model.StudentsGrades;
            for (int i = 0; i < gradeList.Count; i++)
            {
                gradeList[i].FirstMark = modelData[i].FirstMark;
                gradeList[i].MidtMark = modelData[i].MidtMark;
                gradeList[i].FinalMark = modelData[i].FinalMark;
                gradeList[i].ActivityMark = modelData[i].ActivityMark;
            }
            _context.Grades.UpdateRange(gradeList);
            try
            {
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                ViewData["errors"] = "An Error Occurs, Please Try Again...";
                return View(model);

            }

        }













        private async Task<List<Subject>> GetSubjecsAsync()
        {
            var user = await _userManager.GetUserAsync(User);
            var userId = user.TeacherId;

            var subjects = await _context.Subjects
                .Include(c => c.Class).Include(s => s.SubjectDetails).Include(t => t.Teacher).OrderBy(b => b.StartTime)
                .Where(s => s.TeacherId == userId).ToListAsync();

            return subjects;
        }
    }
}

ProjetFinEtude/Views/Grades/GiveMarks.cshtml
@model AddGradeViewModel
@{
    ViewData["Title"] = "Give Marks";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>Give Marks</h2>
<hr />


<div class="row">
    <div class="col-xl-3 col-md-6 col-sm-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Class
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.ClassName</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-graduation-cap fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>  <div class="col-xl-3 col-md-6 col-sm-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Subject Name
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.SubjectName</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-book fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <form asp-action="GiveMarks" method="post">
            <input type="hidden" asp-for="@Model.ClassName" />
            <input type="hidden" asp-for="@Model.SubjectName" />
            <div class="card shadow mb-4">
                <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                    <h6 class="m-0 font-weight-bold text-primary">
                        <span class="text-danger">@ViewBag.errors</span>
                    </h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th scope="col">Student</th>
                                    <th scope="col">Activity(10)</th>
                                    <th scope="col">First Mark(20)</th>
                                    <th scope="col">Mid Mark(20)</th>
                                    <th scope="col">Final Mark(50)</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th scope="col">Student</th>
                                    <th scope="col">Activity Mark</th>
                                    <th scope="col">First Mark</th>
                                    <th scope="col">Mid Mark</th>
                                    <th scope="col">Final Mark</th>
                                </tr>
                            </tfoot>
                            <tbody>
                                @for (int i = 0; i < Model.StudentsGrades.Count; i++)
                                {
                                    <tr>

                                        <td>
                                            <input type="hidden" asp-for="@Model.StudentsGrades[i].StudentId" />
                                            @Model.StudentsGrades[i].StudentName
                                        </td>
                                        <td>
                                            <input asp-for="@Model.StudentsGrades[i].ActivityMark" type="number" min="0" max="10" class="form-control" />
                                        </td>
                                        <td>
                                            <input asp-for="@Model.StudentsGrades[i].FirstMark" type="number" min="0" max="20" class="form-control" />
                                        </td>
                                        <td>
                                            <input asp-for="@Model.StudentsGrades[i].MidtMark" type="number" min="0" max="20" class="form-control" />
                                        </td>
                                        <td>
                                            <input asp-for="@Model.StudentsGrades[i].FinalMark" type="number" min="0" max="50" class="form-control" />
                                            <input asp-for="@Model.StudentsGrades[i].GradeId" type="hidden" />
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="card-footer text-muted">
                    <input type="submit" value="Save" class="btn btn-primary" />
                    <a asp-action="Index" asp-controller="Grades" class="btn btn-outline-secondary">Back</a>
                </div>
            </div>
        </form>
    </div>
</div>

ProjetFinEtude/Views/Grades/Index.cshtml
@model IEnumerable<Subject>

@{
    ViewData["Title"] = "Give Marks";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>Give Marks</h2>
<hr />
<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary">
                    Current Courses
                </h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th scope="col">Class</th>
                                <th scope="col">Subject</th>
                                <th scope="col">Time</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th scope="col">Class</th>
                                <th scope="col">Subject</th>
                                <th scope="col">Time</th>
                                <th scope="col">Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Class.Name</td>
                                    <td>@item.SubjectDetails.Name</td>
                                    <td>
                                        @( $"{item.StartTime.ToString(@"hh\:mm")} - {item.EndTime.ToString(@"hh\:mm")}" )
                                    </td>
                                    <td class="text-nowrap">
                                        <a asp-controller="Grades"
                                           asp-action="GiveMarks"
                                           asp-route-id="@item.Id"
                                           class="btn btn-outline-primary btn-sm"><i class="fas fa-award"></i> Give Marks</a>
                                        <a asp-controller="Grades"
                                           asp-action="ViewMarks"
                                           asp-route-id="@item.Id"
                                           class="btn btn-outline-secondary btn-sm"><i class="fas fa-eye"></i> View Marks</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer text-muted">


            </div>
        </div>
    </div>
</div>

ProjetFinEtude/Views/Grades/ViewMarks.cshtml
@model AddGradeViewModel
@{
    ViewData["Title"] = "View Marks";
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}

<h2>View Marks</h2>
<hr />


<div class="row">
    <div class="col-xl-3 col-md-6 col-sm-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Class
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.ClassName</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-graduation-cap fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 col-sm-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Subject Name
                        </div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">@Model.SubjectName</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-book fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @if (Model.ClassAvarage > 0)
    {
        <div class="col-xl-3 col-md-6 col-sm-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Course Avarage
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800" style="font-size:30px">
                                <span> @Model.ClassAvarage</span>
                                @{
                                    var maxMark = 100;
                                    if (Model.ClassAvarage >= maxMark * 0.90)
                                    {
                                        <i class="fas fa-thermometer-full text-success"></i>
                                    }
                                    else if (maxMark * 0.84 <= Model.ClassAvarage)
                                    {
                                        <i class="fas fa-thermometer-three-quarters text-success"></i>
                                    }
                                    else if (maxMark * 0.84 > Model.ClassAvarage && maxMark * 0.70 <= Model.ClassAvarage)
                                    {
                                        <i class="fas fa-thermometer-half text-primary"></i>
                                    }
                                    else if (maxMark * 0.5 <= Model.ClassAvarage && maxMark * 0.70 > Model.ClassAvarage)
                                    {
                                        <i class="fas fa-thermometer-quarter text-warning"></i>
                                    }
                                    else if (maxMark * 0.5 > Model.ClassAvarage)
                                    {
                                        <i class="fas fa-thermometer-empty text-danger"></i>
                                    }
                                }
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-tachometer-alt fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card shadow mb-4">
            <div class="card-header py-3 d-flex flex-wrap justify-content-between align-items-center">
                <h6 class="m-0 font-weight-bold text-primary">
                    Give Marks
                </h6>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                            <tr>
                                <th scope="col">Student</th>
                                <th scope="col">Activity</th>
                                <th scope="col">First Mark</th>
                                <th scope="col">Mid Mark</th>
                                <th scope="col">Final Mark</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th scope="col">Avarage</th>
                                <th scope="col"></th>
                                <th scope="col">
                                    <span>@Model.FirstAvarage</span>
                                    @{
                                        var maxMark2 = 20;
                                        if (Model.FirstAvarage >= maxMark2 * 0.90)
                                        {
                                            <i class="fas fa-thermometer-full text-success"></i>
                                        }
                                        else if (maxMark2 * 0.84 <= Model.FirstAvarage)
                                        {
                                            <i class="fas fa-thermometer-three-quarters text-success"></i>
                                        }
                                        else if (maxMark2 * 0.84 > Model.FirstAvarage && maxMark2 * 0.70 <= Model.FirstAvarage)
                                        {
                                            <i class="fas fa-thermometer-half text-primary"></i>
                                        }
                                        else if (maxMark2 * 0.5 <= Model.FirstAvarage && maxMark2 * 0.70 > Model.FirstAvarage)
                                        {
                                            <i class="fas fa-thermometer-quarter text-warning"></i>
                                        }
                                        else if (maxMark2 * 0.5 > Model.FirstAvarage)
                                        {
                                            <i class="fas fa-thermometer-empty text-danger"></i>
                                        }
                                    }
                                </th>
                                <th scope="col">
                                    <span>@Model.MidAvarage</span>

                                    @{
                                        var maxMark3 = 20;
                                        if (Model.MidAvarage >= maxMark3 * 0.90)
                                        {
                                            <i class="fas fa-thermometer-full text-success"></i>
                                        }
                                        else if (maxMark3 * 0.84 <= Model.MidAvarage)
                                        {
                                            <i class="fas fa-thermometer-three-quarters text-success"></i>
                                        }
                                        else if (maxMark3 * 0.84 > Model.MidAvarage && maxMark3 * 0.70 <= Model.MidAvarage)
                                        {
                                            <i class="fas fa-thermometer-half text-primary"></i>
                                        }
                                        else if (maxMark3 * 0.5 <= Model.MidAvarage && maxMark3 * 0.70 > Model.MidAvarage)
                                        {
                                            <i class="fas fa-thermometer-quarter text-warning"></i>
                                        }
                                        else if (maxMark3 * 0.5 > Model.MidAvarage)
                                        {
                                            <i class="fas fa-thermometer-empty text-danger"></i>
                                        }
                                    }
                                </th>
                                <th scope="col">
                                    <span>@Model.FinalAvarage</span>
                                    @{
                                        var maxMark4 = 40;
                                        if (Model.FinalAvarage >= maxMark3 * 0.90)
                                        {
                                            <i class="fas fa-thermometer-full text-success"></i>
                                        }
                                        else if (maxMark4 * 0.84 <= Model.FinalAvarage)
                                        {
                                            <i class="fas fa-thermometer-three-quarters text-success"></i>
                                        }
                                        else if (maxMark4 * 0.84 > Model.FinalAvarage && maxMark4 * 0.70 <= Model.FinalAvarage)
                                        {
                                            <i class="fas fa-thermometer-half text-primary"></i>
                                        }
                                        else if (maxMark4 * 0.5 <= Model.FinalAvarage && maxMark4 * 0.70 > Model.FinalAvarage)
                                        {
                                            <i class="fas fa-thermometer-quarter text-warning"></i>
                                        }
                                        else if (maxMark4 * 0.5 > Model.FinalAvarage)
                                        {
                                            <i class="fas fa-thermometer-empty text-danger"></i>
                                        }
                                    }
                                </th>
                                <th scope="col"> </th>

                            </tr>
                        </tfoot>
                        <tbody>
                            @foreach (var item in Model.StudentsGrades)
                            {
                                <tr>
                                    <td>@item.StudentName</td>
                                    <td>@item.ActivityMark</td>
                                    <td>@item.FirstMark</td>
                                    <td>@item.MidtMark</td>
                                    <td>@item.FinalMark</td>
                                    <td>@item.Total</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer text-muted">
                <a asp-action="Index" class="btn btn-secondary">Back</a>
            </div>

        </div>
    </div>
</div>